FROM jupyter/datascience-notebook

RUN pip install joblib

RUN mkdir model
ENV MODEL_DIR=/home/jovyan/model
ENV MODEL_FILE=regr.joblib
ENV METADATA_FILE=metadata.json

COPY train.py ./train.py
COPY inference.py ./inference.py

RUN python3 train.py
